name: Render

on:
  push:
    branches:
      - main

jobs:
  render-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any other version you need

      - name: Install Open Sans font
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-open-sans

      - name: Install dependencies
        run: yarn install

      - name: Run the render script
        run: yarn run render

      - name: Run the build-browser script
        run: yarn run build-browser

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add rendered/
          git add browser/src/assets/fs.json
          git add docs/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Automated render and commit'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
